language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "make"
script: "make test"
cache: pip
jobs:
  include:
    - stage: test
      python: 3.6
      script: "make coverage"
    - stage: coverage
      python: 3.6
      script: codecov
