env:
  global:
    - NEWEST_PYTHON=3.6
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "make"
script: "make coverage"
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON ]]; then codecov; fi
