swagger: "2.0"
info:
  title: Hello API
  version: "0.1"
paths:
  /greeting:
    get:
      operationId: api.say_hello
      summary: Returns a greeting.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: name
          in: query
          type: string
          required: true
        - name: game_of_choice
          in: query
          type: string
      responses:
        "200":
          description: Successful response.
          schema:
            type: object
            required:
              - weekend_greeting
              - pizza_party
            properties:
              weekend_greeting:
                type: string
                description: Huzzah!
              pizza_party:
                type: integer
                description: Number of pizzas you'll consume this weekend.
              favorite_drink:
                type: string
                description: Your favorite drink.
